nelmio_api_doc:
    documentation:
        info:
            title: Money Converter
            description: Sample English Currency Converter
            version: 0.1.1
        servers:
          - url: http://money-converter.local:8083
            description: Local API
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc|/doc\.json$) # Accepts routes under /api except /api/doc