App\Entity\Article:
    exclusion_policy: all
    relations:
        - rel: self
          href:
              route: api_get_article
              parameters:
                  code: expr(object.getCode())
                  _format: json
              absolute: false
          exclusion:
              groups: [ hateoas ]
        - rel: photo
          embedded: expr(service('app.article_service').getPhoto(object, true))
          exclusion:
              exclude_if: expr(object.getPhotoFilename() === null)
              groups: [ article ]
    properties:
        name:
            expose: true
            groups: [ articles, article ]
        description:
            expose: true
            groups: [ articles, article ]
        code:
            expose: true
            groups: [ articles, article ]
        price:
            expose: true
            type: string
            groups: [ articles, article ]
        catalogs:
            expose: true
            groups: [ article.catalogs ]
    virtual_properties:
        getUuid:
            serialized_name: id
            groups: [ articles, article ]