App\Entity\Catalog:
    exclusion_policy: all
    relations:
        - rel: self
          href:
              route: api_get_catalog
              parameters:
                  slug: expr(object.getSlug())
                  _format: json
              absolute: false
          exclusion:
              groups: [ hateoas ]
    properties:
        name:
            expose: true
            groups: [ catalogs, catalog ]
        description:
            expose: true
            groups: [ catalogs, catalog ]
        slug:
            expose: true
            groups: [ catalogs, catalog ]
        articles:
            expose: true
            groups: [ catalog.articles ]
    virtual_properties:
        getUuid:
            serialized_name: id
            groups: [ catalog ]